# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['app.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('sector_data.py', '.'),
        ('pdf_generator.py', '.'),
        ('requirements.txt', '.')
    ],
    hiddenimports=[
        'importlib.metadata',
        'streamlit',
        'pandas',
        'numpy',
        'plotly',
        'reportlab',
        'PIL',
        'streamlit.web',
        'streamlit.runtime',
        'streamlit.runtime.scriptrunner',
        'streamlit.runtime.caching',
        'streamlit.elements',
        'streamlit.runtime.stats',
        'streamlit.runtime.secrets',
        'streamlit.components.v1',
        'click',
        'rich',
        'jinja2',
        'google.protobuf',
        'grpcio',
        'altair',
        'pyarrow',
        'markdown',
        'tornado',
        'werkzeug',
        'cachetools',
        'gitpython',
        'pydeck',
        'validators',
        'semver',
        'plotly.graph_objects',
        'plotly.utils',
        'plotly.validators',
        'reportlab.pdfgen',
        'reportlab.pdfbase',
        'reportlab.lib',
        'PIL._imaging'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Financial_Audit_Assistant',
    debug=True,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
